apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
  namespace "modules.videooverlay"
  compileSdkVersion 36

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 36
  }

  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlinVersion"
}
