import { SparkMetadata } from "../types/spark";

export const sparkMetadata: Record<string, SparkMetadata> = {
    spinner: {
        id: "spinner",
        title: "Decision Spinner",
        description: "Make decisions with customizable spinning wheel",
        icon: "🎡",
        category: "utility",
        createdAt: "2024-01-01T00:00:00.000Z",
        rating: 4.2,
    },
    flashcards: {
        id: "flashcards",
        title: "Spanish Cards",
        description: "Study with interactive flip cards and progress tracking",
        icon: "🃏",
        category: "spanish",
        createdAt: "2024-01-02T00:00:00.000Z",
        rating: 4.6,
    },
    "packing-list": {
        id: "packing-list",
        title: "Packing List",
        description: "Organize and track your travel or trip packing items",
        icon: "🎒",
        category: "productivity",
        createdAt: "2024-01-04T00:00:00.000Z",
        rating: 4.3,
    },
    todo: {
        id: "todo",
        title: "Todo List",
        description: "Organize tasks with due dates and completion tracking",
        icon: "📝",
        category: "productivity",
        secondaryCategory: "golf",
        createdAt: "2024-01-05T00:00:00.000Z",
        rating: 4.7,
    },
    toview: {
        id: "toview",
        title: "Toview",
        description: "Track movies, books, and shows to watch with view dates",
        icon: "👁️",
        category: "media",
        createdAt: "2024-01-06T00:00:00.000Z",
        rating: 4.1,
    },
    "food-cam": {
        id: "food-cam",
        title: "FoodCam",
        description: "Visual food diary with photo timeline and camera integration",
        icon: "📸",
        category: "health",
        createdAt: "2024-01-07T00:00:00.000Z",
        rating: 4.4,
    },
    "spanish-friend": {
        id: "spanish-friend",
        title: "Amigo",
        description: "Practice Spanish conversation with Ana and Miguel",
        icon: "🇪🇸",
        category: "spanish",
        createdAt: "2024-01-08T00:00:00.000Z",
        rating: 4.5,
    },
    "tee-time-timer": {
        id: "tee-time-timer",
        title: "Tee Time Timer",
        description: "Nail your golf prep routine",
        icon: "⛳️⏰",
        category: "golf",
        createdAt: "2024-01-09T00:00:00.000Z",
        rating: 4.0,
    },
    soundboard: {
        id: "soundboard",
        title: "Sound Board",
        description: "Record and play custom sound clips with categories",
        icon: "🎛️",
        category: "media",
        createdAt: "2024-01-10T00:00:00.000Z",
        rating: 3.8,
    },
    "golf-brain": {
        id: "golf-brain",
        title: "Golf Brain",
        description: "Track golf rounds with detailed shot analysis and course management",
        icon: "🏌️‍♂️",
        category: "golf",
        createdAt: "2024-01-11T00:00:00.000Z",
        rating: 4.5,
    },
    "quick-convert": {
        id: "quick-convert",
        title: "Quick Convert",
        description: "Currency conversion tool with configurable exchange rates and denominations",
        icon: "💱",
        category: "utility",
        createdAt: "2024-01-12T00:00:00.000Z",
        rating: 3.9,
    },
    "spanish-reader": {
        id: "spanish-reader",
        title: "Spanish Reader",
        description: 'Learn to read Spanish with interleaved English and Spanish text from "To Build a Fire"',
        icon: "📖",
        category: "spanish",
        createdAt: "2024-01-13T00:00:00.000Z",
        rating: 4.3,
    },
    "trip-story": {
        id: "trip-story",
        title: "TripStory",
        description: "Plan, remember, and share your trip with pics...lots and lots of picsS",
        icon: "✈️",
        category: "travel",
        secondaryCategory: "golf",
        createdAt: "2024-01-14T00:00:00.000Z",
        rating: 4.8,
    },
    "short-saver": {
        id: "short-saver",
        title: "Short Saver",
        description: "Save and organize your favorite YouTubes",
        icon: "🎬",
        category: "media",
        secondaryCategory: "golf",
        createdAt: "2024-01-15T00:00:00.000Z",
        rating: 4.5,
        properties: ["Shareable"],
    },
    "song-saver": {
        id: "song-saver",
        title: "Song Saver",
        description: "Save and organize your favorite Spotify tracks",
        icon: "🎵",
        category: "media",
        createdAt: "2024-11-21T00:00:00.000Z",
        rating: 4.5,
    },
    "spark-wizard": {
        id: "spark-wizard",
        title: "Spark Wizard",
        description: "Submit your own Spark idea and become a product manager",
        icon: "🧙‍♂️",
        category: "community",
        createdAt: "2024-01-16T00:00:00.000Z",
        rating: 4.5,
    },
    "minute-minder": {
        id: "minute-minder",
        title: "Minute Minder",
        description: "Track your daily activities with start times and countdown timers",
        icon: "⏳",
        category: "productivity",
        secondaryCategory: "golf",
        createdAt: "2024-01-17T00:00:00.000Z",
        rating: 4.0,
    },
    "buzzy-bingo": {
        id: "buzzy-bingo",
        title: "Buzzy Bingo",
        description: "Buzzword bingo game - mark squares as you hear tech terms",
        icon: "🐝",
        category: "game",
        createdAt: "2025-11-01T00:00:00.000Z",
        rating: 4.5,
        properties: ["AI"],
    },
    memory: {
        id: "memory",
        title: "Memory",
        description: "Classic memory matching game with emoji cards",
        icon: "🧠",
        category: "game",
        createdAt: "2025-12-26T00:00:00.000Z",
        rating: 4.5,
    },
    "card-score": {
        id: "card-score",
        title: "CardScore",
        description: "Fast, simple scorekeeping for card games",
        icon: "♠️",
        category: "utility",
        secondaryCategory: "golf",
        createdAt: "2025-11-01T00:00:00.000Z",
        rating: 4.0,
    },
    golfWisdom: {
        id: "golfWisdom",
        title: "Golf Wisdom",
        description: "Inspirational golf wisdom from Tam O'Shanter",
        icon: "📖",
        category: "golf",
        createdAt: "2025-12-01T00:00:00.000Z",
        rating: 4.3,
    },
    "weight-tracker": {
        id: "weight-tracker",
        title: "Weight Tracker",
        description: "Track your weight, set goals, and visualize progress",
        icon: "⚖️",
        category: "health",
        createdAt: "2025-12-01T00:00:00.000Z",
        rating: 4.5,
    },
    "share-sparks": {
        id: "share-sparks",
        title: "Share Sparks",
        description: "Share the Sparks app with friends",
        icon: "⚡️",
        category: "utility",
        createdAt: "2025-12-01T00:00:00.000Z",
        rating: 4.5,
    },
    "coming-up": {
        id: "coming-up",
        title: "Coming Up",
        description: "Track upcoming birthdays, anniversaries, and big days",
        icon: "🗓️",
        category: "utility",
        secondaryCategory: "golf",
        createdAt: "2025-12-01T00:00:00.000Z",
        rating: 4.4,
    },
    "final-clock": {
        id: "final-clock",
        title: "Final Clock",
        description: "Countdown to your projected death date based on actuarial data",
        icon: "☠️",
        category: "health",
        createdAt: "2025-12-02T00:00:00.000Z",
        rating: 4.5,
    },
    "trip-survey": {
        id: "trip-survey",
        title: "Trip Survey",
        description: "Plan trips with group input and collaborative decision-making",
        icon: "🧭",
        category: "travel",
        createdAt: "2025-12-02T00:00:00.000Z",
        rating: 4.3,
    },
    "spark-stats": {
        id: "spark-stats",
        title: "Spark Stats",
        description: "Community usage stats and trending sparks",
        icon: "📊",
        category: "community",
        createdAt: "2025-11-03T00:00:00.000Z",
        rating: 4.5,
    },
    skins: {
        id: "skins",
        title: "Skins",
        description: "Track who wins holes on the course with history carryover",
        icon: "⛳️💰",
        category: "golf",
        createdAt: "2025-12-08T00:00:00.000Z",
        rating: 4.5,
    },
    recaipe: {
        id: "recaipe",
        title: "RecAIpe",
        description: "AI-powered recipe generator with shopping and cooking modes",
        icon: "🍳",
        category: "productivity",
        createdAt: "2025-12-06T00:00:00.000Z",
        rating: 4.6,
        properties: ["AI"],
    },
    shop: {
        id: "shop",
        title: "Shop",
        description: "Simple shopping list with editable items and local persistence",
        icon: "🛒",
        category: "productivity",
        createdAt: "2025-12-14T00:00:00.000Z",
        rating: 4.5,
    },
    "speak-spark": {
        id: "speak-spark",
        title: "Speak Spark",
        description: "Control other Sparks with your voice",
        icon: "🎙️",
        category: "productivity",
        createdAt: "2025-12-09T00:00:00.000Z",
        rating: 4.5,
        properties: ["AI"],
    },
    "friend-spark": {
        id: "friend-spark",
        title: "Friend Spark",
        description: "Connect with friends and share sparks",
        icon: "🤝",
        category: "social",
        createdAt: "2025-12-15T00:00:00.000Z",
        rating: 4.5,
    },
    "tripod-spark": {
        id: "tripod-spark",
        title: "The Wolverine",
        description: "Get the ultimate grass-mounting tripod for your swing",
        icon: "📸",
        iconImage: require("../../assets/wolverine_icon.png"),
        category: "golf",
        createdAt: "2025-12-22T00:00:00.000Z",
        rating: 4.4,
    },
    "dream-catcher": {
        id: "dream-catcher",
        title: "Dream Catcher",
        description: "Record and interpret your dreams",
        icon: "🌙",
        category: "health",
        createdAt: "2025-12-27T00:00:00.000Z",
        rating: 4.5,
        properties: ["AI"],
    },
    "goal-tracker": {
        id: "goal-tracker",
        title: "Goal Tracker",
        description: "Track your progress toward annual goals with visual charts",
        icon: "🎯",
        category: "productivity",
        secondaryCategory: "golf",
        createdAt: "2026-01-02T00:00:00.000Z",
        rating: 4.5,
    },
    scorecard: {
        id: "scorecard",
        title: "Scorecard",
        description: "Simple Scorecard Spark",
        icon: "⛳🔢",
        category: "golf",
        createdAt: "2026-01-17T00:00:00.000Z",
        rating: 4.5,
    },
    ideas: {
        id: "ideas",
        title: "Ideas",
        description: "Capture and organize your ideas with markdown support",
        icon: "💡",
        category: "productivity",
        createdAt: "2026-01-17T00:00:00.000Z",
        rating: 4.5,
    },
    "business-spark": {
        id: "business-spark",
        title: "Empire",
        description: "Build a 3D printing empire from nothing. Learn accounting through bold business moves.",
        icon: "💼",
        category: "productivity",
        createdAt: "2026-01-23T00:00:00.000Z",
        rating: 4.5,
        properties: ["AI", "Beta"],
    },
    infinite: {
        id: "infinite",
        title: "Infinite",
        description: "The gateway to dynamic, on-demand sparklets.",
        icon: "♾️",
        category: "community",
        createdAt: "2026-01-27T00:00:00.000Z",
        rating: 4.5,
        properties: ["Beta"],
    },
    "record-swing": {
        id: "record-swing",
        title: "Record Swing",
        description: "Standalone swing recorder with voice activation and customizable delay.",
        icon: "🎥🏌️",
        category: "golf",
        createdAt: "2026-02-14T00:00:00.000Z",
        rating: 4.2,
        properties: ["Beta"],
    },
    "video": {
        id: "video",
        title: "Video",
        description: "Record and edit videos for social media shorts.",
        icon: "🎬✨",
        category: "media",
        createdAt: "2026-02-28T00:00:00.000Z",
        rating: 0.0,
        properties: ["AI", "Beta"],
    },
};

export const getSparkMetadataById = (id: string) => {
    return sparkMetadata[id];
};
